### ISSUE TITLE
powermetter

### ISSUE THREAD

**Issue by patmtp35** [matlen67/soyosource-weblimiter#1]
hi, 
thanks for this project !
was it possible to extract powermeter value like DC Voltage Batterie or ampere ?
i wana use them in homee assitant or jeedom 

regards

**Comment by matlen67** [comment]
Unfortunately I have not yet managed to get the Soyo to send data via RS485 and provide this information (FW: STC8-2022-0801).

**Comment by patmtp35** [comment]
ok thanks
________________________________
De : matlen67 ***@***.***>
Envoyé : dimanche 12 février 2023 10:37
À : matlen67/soyosource-weblimiter ***@***.***>
Cc : Patrick ***@***.***>; Author ***@***.***>
Objet : Re: [matlen67/soyosource-weblimiter] powermetter (Issue #1)


Unfortunately I have not yet managed to get the Soyo to send data via RS485 and provide this information (FW: STC8-2022-0801).
