### ISSUE TITLE
TTL XY-017

### ISSUE THREAD

**Issue by svenessar** [matlen67/soyosource-weblimiter#9]
Hallo,

ich würde gern einen TTL XY-017 nutzen. Das ist der den ich von Amazon gekauft habe: https://amzn.eu/d/gxYIneq

was und wie müsste ich den Code anpassen, dass das läuft?

Vielen Dank

**Comment by matlen67** [comment]
Moin, ich wüsste jetzt nicht was da am Code geändert werden sollte. Das Teil wandelt ja genau so wie der Wandler den ich nutze den RS232 TTL Pegel in RS485 um. Bei deinem entfällt sogar die Steuerung ob Senden oder Empfangen. Da die neuen Soyos eh nix mehr senden ist es eh egal. Hast schon zusammengelötet und geht nicht?--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 10.05.23, 19:49 schrieb svenessar ***@***.***>:

   
  Hallo, 
  ich würde gern einen TTL XY-017 nutzen. Das ist der den ich von Amazon gekauft habe: https://amzn.eu/d/gxYIneq 
  was und wie müsste ich den Code anpassen, dass das läuft? 
  Vielen Dank

**Comment by svenessar** [comment]
vielen dank für deine antwort. 
ja ich habe alles zusammengebaut und es funktioniert leider nicht. 
ich will mit deinem projekt das von https://github.com/KlausLi/Esp-Soyosource-Controller ersetzen.


jetzt habe mir das von dir empfohlene TTL Modul bei amazon gekauft: https://www.amazon.de/dp/B07DK4QG6H/ref=pe_27091401_487024491_TE_item

ist das diesmal das richtig?

lg
sven

**Comment by matlen67** [comment]
Moin, ja das nutze ich auch. Gibts denn mit dem Projekt von Klaus Probleme? Bei mir hat sich das immer nach 1 , 2 Tagen aufgehängt. Und da es da kein Source zu gibt und funktionsmäßig recht überladen ist bin ich angefangen mir selber was zu basteln. Ich steuere eh alles über iobroker und brauchte nur die MQTT Steuerung. Aktuell versuche ich mich noch an einen Timer so dass das Modul dem Soyo tu zweit Zeiten unterschiedliche Leistung zuspielt. Ist aber recht komplex alles über ein Webformular zu steuern Gruß matlen67Gruß matlen--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 10.05.23, 20:49 schrieb svenessar ***@***.***>:

   
  vielen dank für deine antwort. ja ich habe alles zusammengebaut und es funktioniert leider nicht. ich will mit deinem projekt das von https://github.com/KlausLi/Esp-Soyosource-Controller ersetzen. 
  jetzt habe mir das von dir empfohlene TTL Modul bei amazon gekauft: https://www.amazon.de/dp/B07DK4QG6H/ref=pe_27091401_487024491_TE_item 
  ist das diesmal das richtig? 
  lg sven

**Comment by svenessar** [comment]
Guten Morgen :-),

mit den Image von Klaus habe ich nur das Problem (kombi Shelly 3EM), dass die Null Einspeisung nicht richtig funktioniert (obwohl es sehr einfach sein sollte). 
Ich hatte sehr oft negative Werte die mich einfach nur geärgert haben.

Shelly MQTT ist mir zu langsam (auch mit update_interval = 0), eigentlich brauche ich eine OnDemand Benachrichtigung für Wertänderungen. Geht damit scheinbar aber nicht.. Also bleibt vorerst nur ein HTTP Client.

Vom Klaus Projekt nutze ich nur den statischen Teil, setze die Werte über ein weiteren ESP32 per Http. 
Das ist aber mist, weil ich das komplett im Griff haben möchte....
Eine Anfrage für den SourceCode vom Klaus wurde blöde Antworten beantwortet, naja..


UND dann..... fand ich dein Projekt :-) Was mir Hoffnung gegeben hat. 
Vielen Dank für deine Arbeit 👍 

Ich halte dich auf dem laufenden, wenn ich den TTL fertig bei mir habe.

LG
Sven

**Comment by svenessar** [comment]
Sorry,
eine Frage hätte ich noch, warum hast du 500ms gewählt um den Soyo zu setzen?
LG
Sven

**Comment by matlen67** [comment]
Weil der original Limiter das auch macht. Bin aber mittlerweile hier zum Testen bei 1000ms. Funktioniert auch tadelos.--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 12.05.23, 18:18 schrieb svenessar ***@***.***>:

   
  Sorry, eine Frage hätte ich noch, warum hast du 500ms gewählt um den Soyo zu setzen? LG Sven
